#!/usr/bin/env python3
"""Generate src/ivx_voices.inc, the built-in Infovox 230 voice table.

The table is the engine's own mode table: every entry here is written verbatim
into the virtual registry the engine reads its configuration from, so the field
names are the engine's, not ours (see the strings in Ivx230nt.dll:
ModeGUID, LanguageID, LanguageFile, LibraryFile, PhSymFile, DiphoneFile,
MappingFile, SpeakerName, SpeakerStyle, Gender, Age, Pitch, Dynamic,
Aspiration, FormantNo).

Source of truth is bin/infovox230/modes.json, the table extracted from a
working Infovox 230 installation. Regenerate with:

    python tools/gen_voice_table.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MODES = os.path.join(ROOT, "bin", "infovox230", "modes.json")
OUT = os.path.join(ROOT, "src", "ivx_voices.inc")

# SAPI5 wants a full LCID. The engine's LanguageID is sometimes a full LCID
# (1033, 2057) and sometimes a bare primary language id (10 = Spanish). Fill in
# SUBLANG_DEFAULT for the bare ones, which is the same rule the NVDA add-on
# uses, so both front ends agree on what language a voice is.
def to_lcid(language_id):
    lid = int(language_id)
    if lid > 0x3FF:
        return lid
    return 0x0400 | lid


# Display name in the Windows voice list. The engine's mode name already reads
# well ("American English Male"); the prefix is what makes it identifiable when
# it sits in a list next to other vendors' voices.
def display_name(mode_name):
    return "Infovox " + mode_name


# The engine will only accept a mode whose key name begins with the name of the
# language that mode is for -- measured in tools/probe_custom_modes.py, where
# renaming a stock mode made it vanish from the enumerator and "<language>
# anything" was accepted for all twelve languages. Every stock mode is named
# "<language> <speaker>", so the language name is everything but the last word.
# User-defined voices are named from this.
SPEAKERS = ("Male", "Female", "Child", "Giant", "Zombie")


def language_name(mode_name):
    head, _, tail = mode_name.rpartition(" ")
    if tail not in SPEAKERS:
        raise ValueError("unexpected mode name %r" % mode_name)
    return head


def c_str(s):
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            raise ValueError("non-ASCII in %r; the engine config is ANSI" % s)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main():
    with open(MODES, "r", encoding="utf-8") as f:
        modes = json.load(f)

    modes.sort(key=lambda m: m["_name"])

    lines = []
    lines.append("// Generated by tools/gen_voice_table.py -- do not edit by hand.")
    lines.append("// Built-in Infovox 230 mode table (%d voices)." % len(modes))
    lines.append("")
    lines.append("// clang-format off")
    lines.append("static const ivx::BuiltinVoice kBuiltinVoices[] = {")

    for m in modes:
        name = m["_name"]
        lcid = to_lcid(m["LanguageID"])
        fields = [
            c_str(name),                       # mode key name / engine mode name
            c_str(display_name(name)),         # SAPI5 token name
            c_str(language_name(name)),        # what a custom mode name must start with
            c_str(m["ModeGUID"]),
            c_str(m["LanguageID"]),
            "0x%04X" % lcid,
            c_str(m["LanguageFile"]),
            c_str(m.get("LibraryFile", "")),
            c_str(m.get("PhSymFile", "")),
            c_str(m.get("DiphoneFile", "")),
            c_str(m.get("MappingFile", "")),
            c_str(m.get("SpeakerName", "")),
            c_str(m.get("SpeakerStyle", "")),
            c_str(m.get("Gender", "")),
            c_str(m.get("Age", "")),
            c_str(m.get("Pitch", "")),
            c_str(m.get("Dynamic", "")),
            c_str(m.get("Aspiration", "")),
            c_str(m.get("FormantNo", "")),
        ]
        lines.append("    { " + ", ".join(fields) + " },")

    lines.append("};")
    lines.append("// clang-format on")
    lines.append("")

    text = "\n".join(lines)
    with open(OUT, "w", encoding="ascii", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d voices)" % (OUT, len(modes)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
