# -*- coding: utf-8 -*-
"""Generate src/translit_tables.inc from the tables verified against the real engines.

Run from the repo root:  python tools/gen_translit.py

Emitting the tables rather than hand-writing them keeps the C++ engine and the Python
reference implementation (tools/translit_ref.py) from drifting apart, and keeps the
generated source pure ascii so it compiles under any codepage.
"""
import io, os, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
import translit_ref as T

def wlit(s):
    # Printable ascii goes through literally; everything else becomes a \uXXXX universal
    # character name, which is exactly four digits and so cannot swallow a following
    # letter the way a \x escape would.
    out = []
    for c in s:
        if c in '"\\':
            out.append("\\" + c)
        elif 0x20 <= ord(c) < 0x7F:
            out.append(c)
        else:
            out.append("\\u%04x" % ord(c))
    return 'L"' + "".join(out) + '"'

def emit_multi(name, rows):
    out = ["static const translit_rule %s[] = {" % name]
    for src, dst in rows:
        out.append('    { L"%s", %d, %s },' % (src, len(src), wlit(dst)))
    out.append("};")
    return "\n".join(out)

def emit_letters(name, d):
    out = ["static const wchar_t* const %s[26] = {" % name]
    for i in range(0, 26, 3):
        out.append("    " + " ".join(
            wlit(d[chr(ord('a') + j)]) + "," for j in range(i, min(i + 3, 26))))
    out.append("};")
    return "\n".join(out)

def emit_words(name, words):
    out = ["static const wchar_t* const %s[] = {" % name]
    for i in range(0, len(words), 3):
        out.append("    " + " ".join(wlit(w) + "," for w in words[i:i + 3]))
    out.append("};")
    return "\n".join(out)

parts = [
    "// Generated by tools/gen_translit.py -- do not edit by hand.",
    "",
    emit_multi("gre_multi", T.GRE_MULTI),
    emit_letters("gre_single", T.GRE_SINGLE),
    emit_letters("gre_names", T.GRE_NAMES),
    "",
    emit_multi("cyr_multi", T.CYR_MULTI),
    emit_letters("cyr_single", T.CYR_SINGLE),
    emit_letters("cyr_names", T.CYR_NAMES),
    "",
    "// Number words for the frontends that cannot read ascii digits at all (Greek and",
    "// Japanese drop them silently, Polish only spells them out digit by digit).",
    emit_words("el_units", T.EL_UNITS),
    emit_words("el_teens", T.EL_TEENS),
    emit_words("el_tens", T.EL_TENS),
    emit_words("el_hundreds", T.EL_HUNDREDS),
    emit_words("pl_units", T.PL_UNITS),
    emit_words("pl_teens", T.PL_TEENS),
    emit_words("pl_tens", T.PL_TENS),
    emit_words("pl_hundreds", T.PL_HUNDREDS),
    emit_words("pl_scales", [w for forms in T.PL_SCALES for w in forms]),
    emit_words("ja_digits", T.JA_DIGITS),
    emit_words("ja_hundreds", T.JA_HUNDREDS),
    emit_words("ja_thousands", T.JA_THOUSANDS),
    emit_words("ja_groups", T.JA_GROUPS),
    emit_words("el_misc", [T.EL_HUNDRED_FLAT, T.EL_THOUSAND, T.EL_THOUSANDS,
                           T.EL_MILLION, T.EL_MILLIONS]),
    emit_words("ja_ten", [T.JA_TEN]),
    "",
]
dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "translit_tables.inc")
io.open(dest, "w", encoding="ascii").write("\n".join(parts) + "\n")
print("wrote", os.path.normpath(dest))
