; Generated by tools/gen_installer_voices.py -- do not edit by hand.
;
; The languages and voices the installer offers, the rule files each
; language needs, and installed.ini -- the record of what was chosen,
; which the catalogue reads back so that Windows is told about those
; voices and no others. Included by Infovox230SAPI.iss.
;
; 60 voices in 12 languages.

[Components]
; A language carries its own rule files, so the size shown against it on
; the components page is the real cost of adding it. The voices inside it
; cost nothing but a name in the Windows voice list: the five speakers of
; a language differ only in four numbers and all five read the same file.
;
; Each voice is named in full rather than just "Male": on that page a
; screen reader reads the line it is on and not the branch above it, and
; "Male" on its own does not say which language it belongs to.

; American English -- AMRULES.IVX, 2.4 MB
Name: "am"; Description: "American English"; Types: full english minimal
Name: "am\male"; Description: "American English Male"; Types: full english minimal
Name: "am\female"; Description: "American English Female"; Types: full english minimal
Name: "am\child"; Description: "American English Child"; Types: full english
Name: "am\giant"; Description: "American English Giant"; Types: full english
Name: "am\zombie"; Description: "American English Zombie"; Types: full english

; British English -- BLRULES.IVX, 0.3 MB
Name: "bl"; Description: "British English"; Types: full english
Name: "bl\male"; Description: "British English Male"; Types: full english
Name: "bl\female"; Description: "British English Female"; Types: full english
Name: "bl\child"; Description: "British English Child"; Types: full english
Name: "bl\giant"; Description: "British English Giant"; Types: full english
Name: "bl\zombie"; Description: "British English Zombie"; Types: full english

; Castilian Spanish -- SPRULES.IVX, 0.0 MB
Name: "sp"; Description: "Castilian Spanish"; Types: full
Name: "sp\male"; Description: "Castilian Spanish Male"; Types: full
Name: "sp\female"; Description: "Castilian Spanish Female"; Types: full
Name: "sp\child"; Description: "Castilian Spanish Child"; Types: full
Name: "sp\giant"; Description: "Castilian Spanish Giant"; Types: full
Name: "sp\zombie"; Description: "Castilian Spanish Zombie"; Types: full

; Danish -- DARULES.IVX, darules.dll, 6.7 MB
Name: "da"; Description: "Danish"; Types: full
Name: "da\male"; Description: "Danish Male"; Types: full
Name: "da\female"; Description: "Danish Female"; Types: full
Name: "da\child"; Description: "Danish Child"; Types: full
Name: "da\giant"; Description: "Danish Giant"; Types: full
Name: "da\zombie"; Description: "Danish Zombie"; Types: full

; Dutch -- duRULES.IVX, 1.9 MB
Name: "du"; Description: "Dutch"; Types: full
Name: "du\male"; Description: "Dutch Male"; Types: full
Name: "du\female"; Description: "Dutch Female"; Types: full
Name: "du\child"; Description: "Dutch Child"; Types: full
Name: "du\giant"; Description: "Dutch Giant"; Types: full
Name: "du\zombie"; Description: "Dutch Zombie"; Types: full

; Finnish -- fiRULES.IVX, 0.0 MB
Name: "fi"; Description: "Finnish"; Types: full
Name: "fi\male"; Description: "Finnish Male"; Types: full
Name: "fi\female"; Description: "Finnish Female"; Types: full
Name: "fi\child"; Description: "Finnish Child"; Types: full
Name: "fi\giant"; Description: "Finnish Giant"; Types: full
Name: "fi\zombie"; Description: "Finnish Zombie"; Types: full

; French -- Frrules.IVX, 0.2 MB
Name: "fr"; Description: "French"; Types: full
Name: "fr\male"; Description: "French Male"; Types: full
Name: "fr\female"; Description: "French Female"; Types: full
Name: "fr\child"; Description: "French Child"; Types: full
Name: "fr\giant"; Description: "French Giant"; Types: full
Name: "fr\zombie"; Description: "French Zombie"; Types: full

; German -- Gerules.ivx, 0.5 MB
Name: "ge"; Description: "German"; Types: full
Name: "ge\male"; Description: "German Male"; Types: full
Name: "ge\female"; Description: "German Female"; Types: full
Name: "ge\child"; Description: "German Child"; Types: full
Name: "ge\giant"; Description: "German Giant"; Types: full
Name: "ge\zombie"; Description: "German Zombie"; Types: full

; Icelandic -- ICRULES.IVX, 0.1 MB
Name: "ic"; Description: "Icelandic"; Types: full
Name: "ic\male"; Description: "Icelandic Male"; Types: full
Name: "ic\female"; Description: "Icelandic Female"; Types: full
Name: "ic\child"; Description: "Icelandic Child"; Types: full
Name: "ic\giant"; Description: "Icelandic Giant"; Types: full
Name: "ic\zombie"; Description: "Icelandic Zombie"; Types: full

; Italian -- ITRULES.IVX, 5.0 MB
Name: "it"; Description: "Italian"; Types: full
Name: "it\male"; Description: "Italian Male"; Types: full
Name: "it\female"; Description: "Italian Female"; Types: full
Name: "it\child"; Description: "Italian Child"; Types: full
Name: "it\giant"; Description: "Italian Giant"; Types: full
Name: "it\zombie"; Description: "Italian Zombie"; Types: full

; Norwegian -- NORULES.IVX, 1.3 MB
Name: "no"; Description: "Norwegian"; Types: full
Name: "no\male"; Description: "Norwegian Male"; Types: full
Name: "no\female"; Description: "Norwegian Female"; Types: full
Name: "no\child"; Description: "Norwegian Child"; Types: full
Name: "no\giant"; Description: "Norwegian Giant"; Types: full
Name: "no\zombie"; Description: "Norwegian Zombie"; Types: full

; Swedish -- Swrules.ivx, 3.3 MB
Name: "sw"; Description: "Swedish"; Types: full
Name: "sw\male"; Description: "Swedish Male"; Types: full
Name: "sw\female"; Description: "Swedish Female"; Types: full
Name: "sw\child"; Description: "Swedish Child"; Types: full
Name: "sw\giant"; Description: "Swedish Giant"; Types: full
Name: "sw\zombie"; Description: "Swedish Zombie"; Types: full

[Files]
; Each language's rule files, installed only if that language was chosen.
Source: "{#StageDir}\engine\AMRULES.IVX"; DestDir: "{app}\engine"; Components: am; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\BLRULES.IVX"; DestDir: "{app}\engine"; Components: bl; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\SPRULES.IVX"; DestDir: "{app}\engine"; Components: sp; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\DARULES.IVX"; DestDir: "{app}\engine"; Components: da; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\darules.dll"; DestDir: "{app}\engine"; Components: da; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\duRULES.IVX"; DestDir: "{app}\engine"; Components: du; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\fiRULES.IVX"; DestDir: "{app}\engine"; Components: fi; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\Frrules.IVX"; DestDir: "{app}\engine"; Components: fr; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\Gerules.ivx"; DestDir: "{app}\engine"; Components: ge; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\ICRULES.IVX"; DestDir: "{app}\engine"; Components: ic; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\ITRULES.IVX"; DestDir: "{app}\engine"; Components: it; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\NORULES.IVX"; DestDir: "{app}\engine"; Components: no; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#StageDir}\engine\Swrules.ivx"; DestDir: "{app}\engine"; Components: sw; Flags: ignoreversion restartreplace uninsrestartdelete

[InstallDelete]
; Runs before anything is copied, so re-running setup with a language
; cleared genuinely gives the disk space back, instead of leaving a rule
; file behind for a voice that is no longer published.
Type: files; Name: "{app}\engine\AMRULES.IVX"; Components: not am
Type: files; Name: "{app}\engine\BLRULES.IVX"; Components: not bl
Type: files; Name: "{app}\engine\SPRULES.IVX"; Components: not sp
Type: files; Name: "{app}\engine\DARULES.IVX"; Components: not da
Type: files; Name: "{app}\engine\darules.dll"; Components: not da
Type: files; Name: "{app}\engine\duRULES.IVX"; Components: not du
Type: files; Name: "{app}\engine\fiRULES.IVX"; Components: not fi
Type: files; Name: "{app}\engine\Frrules.IVX"; Components: not fr
Type: files; Name: "{app}\engine\Gerules.ivx"; Components: not ge
Type: files; Name: "{app}\engine\ICRULES.IVX"; Components: not ic
Type: files; Name: "{app}\engine\ITRULES.IVX"; Components: not it
Type: files; Name: "{app}\engine\NORULES.IVX"; Components: not no
Type: files; Name: "{app}\engine\Swrules.ivx"; Components: not sw

[INI]
; What was chosen, written where the catalogue will read it. Only the
; entries whose component is selected are written, and installed.ini is
; deleted and recreated on every run (see Infovox230SAPI.iss), so the
; file is always the current choice rather than the union of every choice
; ever made. Each key is the name the engine knows that voice by.
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "American English"; String: "1"; Components: am
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "British English"; String: "1"; Components: bl
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "Castilian Spanish"; String: "1"; Components: sp
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "Danish"; String: "1"; Components: da
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "Dutch"; String: "1"; Components: du
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "Finnish"; String: "1"; Components: fi
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "French"; String: "1"; Components: fr
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "German"; String: "1"; Components: ge
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "Icelandic"; String: "1"; Components: ic
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "Italian"; String: "1"; Components: it
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "Norwegian"; String: "1"; Components: no
Filename: "{app}\installed.ini"; Section: "Languages"; Key: "Swedish"; String: "1"; Components: sw

Filename: "{app}\installed.ini"; Section: "Voices"; Key: "American English Male"; String: "1"; Components: am\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "American English Female"; String: "1"; Components: am\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "American English Child"; String: "1"; Components: am\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "American English Giant"; String: "1"; Components: am\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "American English Zombie"; String: "1"; Components: am\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "British English Male"; String: "1"; Components: bl\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "British English Female"; String: "1"; Components: bl\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "British English Child"; String: "1"; Components: bl\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "British English Giant"; String: "1"; Components: bl\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "British English Zombie"; String: "1"; Components: bl\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Castilian Spanish Male"; String: "1"; Components: sp\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Castilian Spanish Female"; String: "1"; Components: sp\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Castilian Spanish Child"; String: "1"; Components: sp\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Castilian Spanish Giant"; String: "1"; Components: sp\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Castilian Spanish Zombie"; String: "1"; Components: sp\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Danish Male"; String: "1"; Components: da\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Danish Female"; String: "1"; Components: da\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Danish Child"; String: "1"; Components: da\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Danish Giant"; String: "1"; Components: da\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Danish Zombie"; String: "1"; Components: da\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Dutch Male"; String: "1"; Components: du\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Dutch Female"; String: "1"; Components: du\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Dutch Child"; String: "1"; Components: du\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Dutch Giant"; String: "1"; Components: du\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Dutch Zombie"; String: "1"; Components: du\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Finnish Male"; String: "1"; Components: fi\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Finnish Female"; String: "1"; Components: fi\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Finnish Child"; String: "1"; Components: fi\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Finnish Giant"; String: "1"; Components: fi\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Finnish Zombie"; String: "1"; Components: fi\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "French Male"; String: "1"; Components: fr\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "French Female"; String: "1"; Components: fr\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "French Child"; String: "1"; Components: fr\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "French Giant"; String: "1"; Components: fr\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "French Zombie"; String: "1"; Components: fr\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "German Male"; String: "1"; Components: ge\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "German Female"; String: "1"; Components: ge\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "German Child"; String: "1"; Components: ge\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "German Giant"; String: "1"; Components: ge\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "German Zombie"; String: "1"; Components: ge\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Icelandic Male"; String: "1"; Components: ic\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Icelandic Female"; String: "1"; Components: ic\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Icelandic Child"; String: "1"; Components: ic\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Icelandic Giant"; String: "1"; Components: ic\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Icelandic Zombie"; String: "1"; Components: ic\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Italian Male"; String: "1"; Components: it\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Italian Female"; String: "1"; Components: it\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Italian Child"; String: "1"; Components: it\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Italian Giant"; String: "1"; Components: it\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Italian Zombie"; String: "1"; Components: it\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Norwegian Male"; String: "1"; Components: no\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Norwegian Female"; String: "1"; Components: no\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Norwegian Child"; String: "1"; Components: no\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Norwegian Giant"; String: "1"; Components: no\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Norwegian Zombie"; String: "1"; Components: no\zombie
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Swedish Male"; String: "1"; Components: sw\male
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Swedish Female"; String: "1"; Components: sw\female
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Swedish Child"; String: "1"; Components: sw\child
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Swedish Giant"; String: "1"; Components: sw\giant
Filename: "{app}\installed.ini"; Section: "Voices"; Key: "Swedish Zombie"; String: "1"; Components: sw\zombie
